--- Scene that demonstrates tessellation of text.

--
-- Permission is hereby granted, free of charge, to any person obtaining
-- a copy of this software and associated documentation files (the
-- "Software"), to deal in the Software without restriction, including
-- without limitation the rights to use, copy, modify, merge, publish,
-- distribute, sublicense, and/or sell copies of the Software, and to
-- permit persons to whom the Software is furnished to do so, subject to
-- the following conditions:
--
-- The above copyright notice and this permission notice shall be
-- included in all copies or substantial portions of the Software.
--
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
-- EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
-- MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
-- IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
-- CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
-- TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
-- SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
--
-- [ MIT license: http://www.opensource.org/licenses/mit-license.php ]
--

-- Modules --
local utils = require("utils")

-- Corona globals --
local timer = timer
local transition = transition

-- Corona modules --
local composer = require("composer")

--
--
--

local Scene = composer.newScene()

local Glyphs = { -- these were generated by the truetype plugin using the Mayan font (https://www.dafont.com/mayan2.font)
	"M",
		"move_to", 702, 646, 
		"line_to", 702, 502, 
		"line_to", 490, -1, 
		"line_to", 453, -5, 
		"line_to", 203, 588, 
		"line_to", 203, 304, 
		"curve_to", 203, 199, 203, 251, 
		"curve_to", 203, 107, 203, 148, 
		"curve_to", 204, 42, 204, 67, 
		"curve_to", 204, 17, 204, 17, 
		"curve_to", 197, 3, 204, 8, 
		"curve_to", 182, -1, 190, -1, 
		"line_to", 117, -1, 
		"curve_to", 68, -2, 91, -1, 
		"curve_to", 38, -2, 46, -2, 
		"line_to", 38, 123, 
		"curve_to", 47, 133, 38, 133, 
		"line_to", 113, 133, 
		"curve_to", 121, 123, 121, 133, 
		"line_to", 121, 70, 
		"curve_to", 107, 61, 121, 61, 
		"curve_to", 93, 70, 93, 61, 
		"line_to", 93, 106, 
		"line_to", 71, 106, 
		"line_to", 71, 21, 
		"line_to", 125, 38, 
		"curve_to", 137, 44, 132, 40, 
		"curve_to", 143, 53, 143, 48, 
		"curve_to", 143, 104, 143, 60, 
		"curve_to", 144, 213, 144, 149, 
		"curve_to", 144, 350, 144, 277, 
		"curve_to", 144, 486, 144, 423, 
		"curve_to", 143, 593, 144, 550, 
		"curve_to", 143, 643, 143, 637, 
		"curve_to", 131, 660, 143, 657, 
		"line_to", 69, 680, 
		"line_to", 68, 702, 
		"curve_to", 188, 698, 140, 697, 
		"curve_to", 260, 702, 237, 700, 
		"line_to", 493, 151, 
		"line_to", 702, 646, 
		"move_to", 738, 640, 
		"line_to", 738, 659, 
		"line_to", 738, 640, 
		"move_to", 912, 19, 
		"line_to", 913, -2, 
		"curve_to", 861, -2, 896, -2, 
		"curve_to", 789, -1, 827, -1, 
		"curve_to", 717, -2, 751, -1, 
		"curve_to", 669, -2, 684, -2, 
		"line_to", 667, 19, 
		"line_to", 725, 37, 
		"curve_to", 738, 54, 736, 40, 
		"line_to", 738, 685, 
		"curve_to", 741, 694, 738, 689, 
		"curve_to", 751, 700, 744, 699, 
		"curve_to", 774, 700, 752, 700, 
		"curve_to", 823, 700, 796, 700, 
		"curve_to", 877, 701, 851, 701, 
		"curve_to", 911, 702, 903, 702, 
		"line_to", 913, 680, 
		"line_to", 850, 660, 
		"curve_to", 838, 643, 838, 657, 
		"curve_to", 838, 612, 838, 639, 
		"curve_to", 837, 545, 838, 586, 
		"curve_to", 837, 454, 837, 505, 
		"curve_to", 837, 350, 837, 403, 
		"curve_to", 837, 246, 837, 297, 
		"curve_to", 837, 153, 837, 195, 
		"curve_to", 838, 85, 838, 112, 
		"curve_to", 838, 53, 838, 58, 
		"curve_to", 852, 38, 838, 41, 
		"line_to", 912, 19,

	"7",
		"move_to", 491, 448, 
		"curve_to", 472, 406, 487, 439, 
		"curve_to", 435, 324, 457, 374, 
		"curve_to", 386, 212, 413, 275, 
		"curve_to", 330, 81, 359, 150, 
		"curve_to", 274, -60, 302, 12, 
		"curve_to", 222, -200, 246, -132, 
		"line_to", 118, -205, 
		"line_to", 115, -201, 
		"line_to", 217, 2, 
		"line_to", 410, 390, 
		"line_to", 79, 390, 
		"line_to", 71, 306, 
		"line_to", 94, 306, 
		"line_to", 94, 341, 
		"curve_to", 98, 348, 94, 346, 
		"curve_to", 107, 350, 102, 350, 
		"curve_to", 117, 347, 113, 350, 
		"curve_to", 121, 341, 121, 345, 
		"line_to", 121, 289, 
		"curve_to", 113, 278, 121, 278, 
		"line_to", 47, 278, 
		"curve_to", 38, 289, 38, 278, 
		"line_to", 30, 466, 
		"curve_to", 248, 468, 150, 467, 
		"curve_to", 330, 468, 290, 468, 
		"curve_to", 404, 469, 371, 469, 
		"curve_to", 460, 469, 437, 469, 
		"curve_to", 489, 470, 483, 470, 
		"line_to", 491, 448,

	"k", 
		"move_to", 585, -2, 
		"curve_to", 526, -1, 551, -1, 
		"curve_to", 484, 0, 501, 0, 
		"curve_to", 459, -1, 473, 0, 
		"curve_to", 427, -1, 445, -1, 
		"curve_to", 407, 30, 418, 14, 
		"curve_to", 383, 65, 396, 47, 
		"curve_to", 310, 161, 348, 114, 
		"curve_to", 233, 255, 273, 208, 
		"line_to", 415, 431, 
		"line_to", 359, 447, 
		"line_to", 357, 467, 
		"curve_to", 413, 465, 389, 466, 
		"curve_to", 453, 465, 437, 465, 
		"curve_to", 493, 465, 467, 465, 
		"curve_to", 558, 467, 519, 466, 
		"line_to", 560, 446, 
		"curve_to", 516, 434, 534, 440, 
		"curve_to", 487, 423, 498, 428, 
		"curve_to", 435, 386, 467, 415, 
		"line_to", 327, 286, 
		"line_to", 489, 83, 
		"curve_to", 532, 38, 519, 49, 
		"curve_to", 553, 28, 540, 33, 
		"curve_to", 584, 19, 566, 24, 
		"line_to", 585, -2, 
		"move_to", 284, -2, 
		"curve_to", 238, -2, 269, -2, 
		"curve_to", 172, -1, 207, -1, 
		"curve_to", 106, -2, 138, -1, 
		"curve_to", 57, -2, 74, -2, 
		"line_to", 54, 19, 
		"line_to", 114, 36, 
		"curve_to", 125, 52, 124, 40, 
		"curve_to", 125, 89, 125, 59, 
		"curve_to", 125, 163, 125, 119, 
		"curve_to", 125, 262, 125, 208, 
		"curve_to", 125, 373, 125, 317, 
		"curve_to", 125, 484, 125, 430, 
		"curve_to", 125, 581, 125, 538, 
		"curve_to", 124, 653, 125, 625, 
		"curve_to", 124, 687, 124, 682, 
		"line_to", 56, 707, 
		"line_to", 52, 708, 
		"line_to", 52, 621, 
		"line_to", 74, 621, 
		"line_to", 74, 657, 
		"curve_to", 78, 663, 74, 661, 
		"curve_to", 88, 666, 83, 666, 
		"curve_to", 97, 663, 93, 666, 
		"curve_to", 102, 657, 102, 661, 
		"line_to", 102, 604, 
		"curve_to", 93, 594, 102, 594, 
		"line_to", 27, 594, 
		"curve_to", 19, 604, 19, 594, 
		"line_to", 19, 716, 
		"curve_to", 75, 727, 41, 721, 
		"curve_to", 143, 740, 110, 734, 
		"curve_to", 223, 755, 182, 747, 
		"curve_to", 222, 712, 223, 746, 
		"curve_to", 221, 631, 222, 679, 
		"curve_to", 221, 523, 221, 583, 
		"curve_to", 221, 402, 221, 464, 
		"curve_to", 221, 282, 221, 341, 
		"curve_to", 221, 174, 221, 223, 
		"curve_to", 221, 93, 221, 126, 
		"curve_to", 221, 51, 221, 60, 
		"curve_to", 234, 33, 223, 36, 
		"line_to", 283, 19, 
		"line_to", 284, -2,

	"s",
		"move_to", 119, 369, 
		"curve_to", 138, 322, 119, 340, 
		"curve_to", 188, 292, 158, 305, 
		"curve_to", 252, 269, 218, 280, 
		"curve_to", 316, 243, 286, 259, 
		"curve_to", 365, 202, 346, 227, 
		"curve_to", 385, 137, 385, 177, 
		"curve_to", 364, 60, 385, 90, 
		"curve_to", 310, 13, 343, 30, 
		"curve_to", 237, -8, 278, -3, 
		"curve_to", 158, -11, 197, -13, 
		"curve_to", 87, 0, 120, -8, 
		"curve_to", 36, 19, 54, 9, 
		"curve_to", 63, 144, 52, 81, 
		"line_to", 63, 145, 
		"curve_to", 72, 155, 63, 155, 
		"line_to", 147, 155, 
		"curve_to", 155, 145, 155, 155, 
		"line_to", 155, 92, 
		"curve_to", 151, 85, 155, 87, 
		"curve_to", 141, 83, 147, 83, 
		"curve_to", 132, 85, 136, 83, 
		"curve_to", 128, 92, 128, 87, 
		"line_to", 128, 128, 
		"line_to", 91, 128, 
		"line_to", 119, 41, 
		"curve_to", 139, 36, 124, 39, 
		"curve_to", 173, 33, 154, 34, 
		"curve_to", 213, 33, 192, 32, 
		"curve_to", 253, 42, 235, 35, 
		"curve_to", 282, 64, 271, 50, 
		"curve_to", 295, 103, 294, 79, 
		"curve_to", 277, 151, 296, 134, 
		"curve_to", 231, 180, 259, 169, 
		"curve_to", 170, 201, 203, 192, 
		"curve_to", 109, 226, 137, 211, 
		"curve_to", 62, 268, 81, 242, 
		"curve_to", 44, 338, 43, 294, 
		"curve_to", 64, 414, 44, 385, 
		"curve_to", 116, 458, 85, 443, 
		"curve_to", 185, 477, 148, 473, 
		"curve_to", 258, 478, 223, 481, 
		"curve_to", 323, 469, 294, 476, 
		"curve_to", 365, 458, 352, 463, 
		"curve_to", 351, 399, 358, 429, 
		"curve_to", 340, 337, 345, 369, 
		"line_to", 321, 333, 
		"line_to", 288, 429, 
		"curve_to", 253, 434, 281, 431, 
		"curve_to", 196, 434, 226, 438, 
		"curve_to", 142, 416, 166, 431, 
		"curve_to", 119, 369, 119, 402,

	"8",
		"move_to", 160, 545, 
		"curve_to", 186, 472, 160, 501, 
		"curve_to", 251, 422, 212, 444, 
		"curve_to", 337, 381, 291, 401, 
		"curve_to", 422, 336, 383, 362, 
		"curve_to", 488, 272, 462, 310, 
		"curve_to", 514, 178, 514, 235, 
		"curve_to", 500, 114, 514, 148, 
		"curve_to", 455, 51, 486, 80, 
		"curve_to", 376, 3, 424, 22, 
		"curve_to", 259, -16, 328, -16, 
		"curve_to", 138, 3, 185, -16, 
		"curve_to", 65, 50, 91, 23, 
		"curve_to", 29, 107, 39, 78, 
		"curve_to", 20, 156, 20, 136, 
		"curve_to", 180, 350, 20, 274, 
		"curve_to", 140, 372, 162, 359, 
		"curve_to", 99, 405, 118, 386, 
		"curve_to", 67, 451, 80, 425, 
		"curve_to", 54, 514, 54, 478, 
		"curve_to", 65, 569, 54, 539, 
		"curve_to", 103, 626, 77, 600, 
		"curve_to", 172, 670, 129, 653, 
		"curve_to", 280, 688, 216, 688, 
		"curve_to", 379, 673, 339, 688, 
		"curve_to", 444, 634, 420, 658, 
		"curve_to", 475, 579, 468, 610, 
		"curve_to", 475, 516, 483, 548, 
		"curve_to", 443, 453, 467, 484, 
		"curve_to", 383, 399, 420, 423, 
		"line_to", 331, 423, 
		"curve_to", 364, 473, 353, 447, 
		"curve_to", 375, 532, 375, 500, 
		"curve_to", 359, 598, 375, 572, 
		"curve_to", 319, 636, 343, 624, 
		"curve_to", 267, 649, 295, 649, 
		"curve_to", 216, 637, 240, 649, 
		"curve_to", 176, 601, 192, 625, 
		"curve_to", 160, 545, 160, 578, 
		"move_to", 125, 168, 
		"curve_to", 146, 83, 125, 116, 
		"curve_to", 200, 37, 168, 51, 
		"curve_to", 269, 25, 232, 23, 
		"curve_to", 338, 42, 306, 27, 
		"curve_to", 390, 85, 370, 58, 
		"curve_to", 409, 150, 410, 113, 
		"curve_to", 389, 220, 407, 192, 
		"curve_to", 344, 268, 371, 248, 
		"curve_to", 285, 302, 317, 288, 
		"curve_to", 224, 332, 253, 317, 
		"curve_to", 125, 168, 125, 272,

	"o",
		"move_to", 311, 477, 
		"curve_to", 359, 462, 328, 474, 
		"curve_to", 421, 423, 391, 450, 
		"curve_to", 474, 353, 452, 397, 
		"curve_to", 497, 243, 497, 309, 
		"curve_to", 471, 117, 497, 167, 
		"curve_to", 407, 38, 445, 68, 
		"curve_to", 326, -3, 369, 9, 
		"curve_to", 251, -14, 284, -14, 
		"curve_to", 177, -3, 218, -14, 
		"curve_to", 101, 35, 136, 8, 
		"curve_to", 42, 109, 66, 63, 
		"curve_to", 18, 228, 18, 156, 
		"curve_to", 34, 328, 18, 286, 
		"curve_to", 75, 398, 50, 370, 
		"curve_to", 131, 443, 101, 427, 
		"curve_to", 191, 468, 162, 460, 
		"curve_to", 243, 479, 220, 477, 
		"curve_to", 278, 479, 267, 481, 
		"line_to", 278, 354, 
		"curve_to", 270, 343, 278, 343, 
		"line_to", 204, 343, 
		"curve_to", 195, 354, 195, 343, 
		"line_to", 195, 407, 
		"curve_to", 199, 413, 195, 411, 
		"curve_to", 208, 416, 203, 416, 
		"curve_to", 218, 413, 214, 416, 
		"curve_to", 223, 407, 223, 411, 
		"line_to", 223, 371, 
		"line_to", 245, 371, 
		"line_to", 245, 439, 
		"curve_to", 209, 432, 231, 438, 
		"curve_to", 168, 405, 188, 426, 
		"curve_to", 135, 345, 149, 385, 
		"curve_to", 121, 238, 121, 305, 
		"curve_to", 135, 129, 121, 171, 
		"curve_to", 170, 64, 149, 88, 
		"curve_to", 215, 33, 191, 41, 
		"curve_to", 261, 25, 240, 25, 
		"curve_to", 357, 75, 322, 25, 
		"curve_to", 393, 232, 393, 125, 
		"curve_to", 382, 322, 393, 286, 
		"curve_to", 358, 380, 372, 358, 
		"curve_to", 331, 413, 345, 403, 
		"curve_to", 311, 427, 318, 424, 
		"line_to", 311, 477, 
		"line_to", 311, 477,
 
	"?",
		"move_to", 179, 191, 
		"curve_to", 151, 220, 165, 205, 
		"curve_to", 124, 253, 137, 236, 
		"curve_to", 98, 303, 98, 288, 
		"curve_to", 106, 331, 98, 317, 
		"curve_to", 114, 346, 109, 339, 
		"curve_to", 125, 361, 119, 353, 
		"curve_to", 137, 376, 131, 369, 
		"curve_to", 152, 392, 144, 384, 
		"line_to", 183, 423, 
		"curve_to", 199, 440, 191, 431, 
		"curve_to", 216, 457, 208, 449, 
		"curve_to", 246, 492, 231, 472, 
		"curve_to", 266, 526, 258, 509, 
		"curve_to", 274, 561, 274, 541, 
		"curve_to", 246, 629, 274, 604, 
		"curve_to", 169, 654, 218, 654, 
		"curve_to", 103, 640, 137, 654, 
		"line_to", 70, 525, 
		"line_to", 50, 522, 
		"line_to", 20, 663, 
		"curve_to", 181, 695, 107, 695, 
		"curve_to", 314, 658, 265, 695, 
		"curve_to", 363, 551, 363, 621, 
		"curve_to", 354, 500, 363, 524, 
		"curve_to", 343, 477, 349, 488, 
		"curve_to", 331, 456, 338, 467, 
		"curve_to", 315, 435, 323, 445, 
		"curve_to", 299, 417, 308, 426, 
		"line_to", 263, 381, 
		"curve_to", 248, 367, 255, 374, 
		"curve_to", 233, 353, 241, 360, 
		"curve_to", 219, 338, 226, 345, 
		"curve_to", 207, 325, 213, 332, 
		"curve_to", 197, 310, 202, 317, 
		"curve_to", 190, 296, 193, 304, 
		"curve_to", 183, 266, 183, 282, 
		"curve_to", 202, 205, 183, 237, 
		"line_to", 179, 191, 
		"move_to", 177, 102, 
		"curve_to", 221, 85, 202, 102, 
		"curve_to", 237, 42, 237, 70, 
		"curve_to", 221, -2, 237, 14, 
		"curve_to", 177, -18, 204, -18, 
		"curve_to", 133, -2, 149, -18, 
		"curve_to", 116, 42, 116, 15, 
		"curve_to", 133, 85, 116, 70, 
		"curve_to", 177, 102, 150, 102
}

local CX, CY = display.contentCenterX - 100, display.contentCenterY + 50

local Count, XScale, YScale = 3, .175, -.175

local FadeParams = { alpha = 1, time = 950 }

local Index

local function DrawCharacter (group, tess)
	for i = group.numChildren, 1, -1 do
		group:remove(i)
	end

	local ti, points, px, py = Index

	repeat
		local what, draw, done = Glyphs[ti]

		if what == "curve_to" then
			local qx, cx = Glyphs[ti + 1], Glyphs[ti + 3]
			local qy, cy = Glyphs[ti + 2], Glyphs[ti + 4]

			for k = 1, Count do
				local t = k / Count
				local s = 1 - t
				local a, b, c = s^2, 2 * s * t, t^2

				points[#points + 1] = CX + (a * px + b * cx + c * qx) * XScale
				points[#points + 1] = CY + (a * py + b * cy + c * qy) * YScale
			end

			ti, px, py = ti + 5, qx, qy
		elseif what == "line_to" then
			ti, px, py = ti + 3, Glyphs[ti + 1], Glyphs[ti + 2]

			points[#points + 1] = CX + px * XScale
			points[#points + 1] = CY + py * YScale
		elseif what == "move_to" then
			ti, px, py = ti + 3, Glyphs[ti + 1], Glyphs[ti + 2]
			draw, points = points, { CX + px * XScale, CY + py * YScale } -- on first move will draw nothing, when points is nil
		else -- 'what' is a character or nil
			done = points -- ignored on opening, when points is nil
			ti, points = ti + 1
		end

		if draw or done then
			tess:AddContour(draw or done)

			if done then
				utils.PolyTris(group, tess, "POSITIVE")

				group.alpha = 0

				transition.to(group, FadeParams)

				Index = what and ti - 1 or 1 -- back up or rewind to put index at next character
			end
		end
	until done
end

-- Show --
function Scene:show (event)
	if event.phase == "did" then
		local tess = utils.GetTess()

		tess:SetOption("CONSTRAINED_DELAUNAY_TRIANGULATION", true) -- can do in any scene, but only showing in this one

		local group = display.newGroup()

		self.view:insert(group)

		self.m_text_group = group

		Index = 1

		self.m_update = timer.performWithDelay(1500, function()
			DrawCharacter(group, tess)
		end, 0)

		DrawCharacter(group, tess)
	end
end

Scene:addEventListener("show")

-- Hide --
function Scene:hide (event)
	if event.phase == "did" then
		utils.GetTess():SetOption("CONSTRAINED_DELAUNAY_TRIANGULATION", false)

		timer.cancel(self.m_update)

		self.m_text_group:removeSelf()
	end
end

Scene:addEventListener("hide")

return Scene