--- Class used intermediately by @{Packing}s, representing an array of packed characters.
-- @classmod CharArray

--
-- Permission is hereby granted, free of charge, to any person obtaining
-- a copy of this software and associated documentation files (the
-- "Software"), to deal in the Software without restriction, including
-- without limitation the rights to use, copy, modify, merge, publish,
-- distribute, sublicense, and/or sell copies of the Software, and to
-- permit persons to whom the Software is furnished to do so, subject to
-- the following conditions:
--
-- The above copyright notice and this permission notice shall be
-- included in all copies or substantial portions of the Software.
--
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
-- EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
-- MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
-- IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
-- CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
-- TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
-- SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
--
-- [ MIT license: http://www.opensource.org/licenses/mit-license.php ]
--

--- Metamethod.
-- @function CharArray:__len
-- @treturn uint Number of characters packed in the array.

--- Get information for rendering a specific character, typically as part of a sequence.
-- @function CharArray:GetPackedQuad
-- @uint char_index Position of character in the array to display, from 1 to `#self`.
-- @number xpos Current position in screen space, x-coordinate...
-- @number ypos ...and y-coordinate.
-- @bool[opt=false] align Align coordinates to integer values?
-- @treturn table Quad to draw, where **x0**, **y0**, contain the upper-left corner and **x1**, **y1**
-- the lower-right. In addition, those values (in order) are remapped to the [0, 1] range as **s0**,
-- **t0**, **s1**, and **t1**, i.e. their texture region.
-- @treturn number New _xpos_ after placing character...
-- @treturn number ...and _ypos_.